version: '3'

services:
  app:
    build: .
    container_name: desafio-next-fullcycle
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
